### PR TITLE
Cleanup of radiation (clouds) - microphysics interaction

### PR DESCRIPTION
**Pull request by climbfuji**
This PR only updates the submodule pointer for ccpp-physics. For a description of the changes, see NOAA-GSD/ccpp-physics#35.

Associated PRs:
NOAA-GSD/ccpp-physics#35
https://github.com/NOAA-GSD/fv3atm/pull/33
https://github.com/NOAA-GSD/ufs-weather-model/pull/26

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing on hera.intel against existing EMC baseline. As expected, the following tests fail (but run to completion; they fail because the GSd suite has changed or no existing baseline), all others pass:
```
fv3_ccpp_thompson_debug
fv3_ccpp_gsd_debug
fv3_ccpp_thompson_no_aero_debug
fv3_ccpp_thompson_no_aero
fv3_ccpp_thompson
fv3_ccpp_gsd
```
[rt_full.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4736955/rt_full.log)
[rt_full_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4736956/rt_full_fail_test.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel against existing GSD baseline (created with current gsd/develop code). The following tests fail (but run to completion):
```
fv3_ccpp_gsd_mynnsfc_debug
fv3_ccpp_gsd_debug
fv3_ccpp_gsd_noah_mynnsfc_debug
fv3_ccpp_mynn
fv3_ccpp_gsd_diag3d_debug
fv3_ccpp_gsd_coldstart
fv3_ccpp_gf_thompson
fv3_ccpp_thompson_mynn
fv3_ccpp_gsd_drag_suite
fv3_ccpp_gsd_sar_25km_debug
fv3_ccpp_gsd
fv3_ccpp_gsd_noah
fv3_ccpp_rap
fv3_ccpp_hrrr
fv3_ccpp_gsd_noah_mynnsfc
fv3_ccpp_gsd_mynnsfc
fv3_ccpp_gsd_warmstart
fv3_ccpp_gsd_sar
```
This is expected, because these tests use combinations of at least two of the three, for which the updated clouds calculation are used: MYNN PBL, Thompson MP, GF CU.


The following tests pass. This is correct, because tests not using both MYNN PBL and GF CU, or not using both MYNN PBL and Thompson MP, should give the same answers.
```
fv3_ccpp_thompson
fv3_ccpp_thompson_no_aero
fv3_ccpp_gf
fv3_ccpp_thompson_no_aero_debug
```
[rt_ccpp_gsd_verify_against_old_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4736990/rt_ccpp_gsd_verify_against_old_baseline.log)
[rt_ccpp_gsd_verify_against_old_baseline_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4736992/rt_ccpp_gsd_verify_against_old_baseline_fail_test.log)

**Comment by climbfuji** [comment]
Manual testing on macOS with gcc+gfortran, clang+gfortran, Python 2.7 and Python 3.7 in PROD and DEBUG mode: code compiles and runs to completion for 2-hour forecasts.

**Comment by climbfuji** [comment]
@tanyasmirnova @hannahcbarnes @joeolson42 @haiqinli please see this PR and associated PRs for the radiation/clouds cleanup code from Tanya and Joe. Everything looking good so far. I will complete the usual regression testing by creating a new baseline using `rt_ccpp_gsd.conf` and then verifying against it (to test run-to-run and restart reproducibility). I will also run Tanya's C768 test case from 20191120 for the head of gsd/develop and the new code and upload some plots. Please look at the changes again, especially the ccpp-physics PR. Thanks!

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf`: first create a new baseline, then verify against it (to test run-to-run and restart reproducibility): all tests pass.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4737451/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4737453/rt_ccpp_gsd_verify.log)

**Comment by climbfuji** [comment]
Here is a comparison (new minus existing) of 2m temperature for a 24h forecast from the 20191120 C768 run. The mean value is 0.00035, i.e. a slight warming signal overall.

Screen Shot 2020-06-05 at 1 37 57 PM

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
