### PR TITLE
add a tracer of coarsepm

### PR DESCRIPTION
**Pull request by haiqinli**
# PR Checklist

- [V ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR. Please consult the ufs-weather-model [wiki](https://github.com/ufs-community/ufs-weather-model/wiki/Making-code-changes-in-the-UFS-weather-model-and-its-subcomponents) if you are unsure how to do this.

- [ V] This PR has been tested using a branch which is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR

- [ V] An Issue describing the work contained in this PR has been created either in the subcomponent(s) or in the ufs-weather-model. The Issue should be created in the repository that is most relevant to the changes in contained in the PR. The Issue and the dependent sub-component PR 
are specified below.

- [ V] Results for one or more of the regression tests change and the reasons for the changes are understood and explained below.

- [ ] New or updated input data is required by this PR. If checked, please work with the code managers to update input data sets on all platforms.

## Instructions: All subsequent sections of text should be filled in as appropriate.

The information provided below allows the code managers to understand the changes relevant to this PR, whether those changes are in the ufs-weather-model repository or in a subcomponent repository. Ufs-weather-model code managers will use the information provided to add any applicable labels, assign reviewers and place it in the Commit Queue. Once the PR is in the Commit Queue, it is the PR owner's responsiblity to keep the PR up-to-date with the develop branch of ufs-weather-model. 

## Description

Add a new tracer of coarsepm, which is mainly from the coarse dust emission.
A bug fix of dust emission from Barry.
An update of smoke/dust direct and indirect feedback.
An update of plumerise.

## Testing

How were these changes tested? What compilers / HPCs was it tested with? Are the changes covered by regression tests? (If not, why? Do new tests need to be added?) Have regression tests and unit tests (utests) been run? On which platforms and with which compilers? (Note that unit tests can only be run on tier-1 platforms)

- [V ] hera.intel
- [ ] hera.gnu
- [ ] orion.intel
- [ ] cheyenne.intel 
- [ ] cheyenne.gnu
- [ ] gaea.intel 
- [ ] jet.intel
- [ ] wcoss_cray
- [ ] wcoss_dell_p3
- [ ] opnReqTest for newly added/changed feature
- [ ] CI

A new tracer is added for the conus13km smoke case.

The regression test log file is /scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS_dev/coarsepm.ufs-weather-model/tests/RegressionTests_hera.intel.log

### CODE REVIEW

**Review by tanyasmirnova — APPROVED** [review]

**Review by joeolson42 — APPROVED** [review]

**Comment by hu5970** [comment]
Hi All, this PR has been approved by Joe and Tanya, We should run regression tests and merge this into GSL repository.
Has anyone run regression tests?

**Comment by haiqinli** [comment]
@hu5970 I have run the regression test run successfully, and the regression test log file is /scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS_dev/coarsepm.ufs-weather-model/tests/RegressionTests_hera.intel.log.

**Comment by hu5970** [comment]
@haiqinli Thanks. I will work on merge this into develop so we can use the new code, fix files, and workflow for RRFS_B runs.

**Comment by hu5970** [comment]
@haiqinli Could you also run regression test on JET for intel and gnu?

**Comment by haiqinli** [comment]
@hu5970 I don't have the experience of running regression test on Jet. Let me give a try.

**Comment by hu5970** [comment]
@haiqinli It should be the same as in Hera. I did it long time ago. Let me know if I can help with something.

**Comment by haiqinli** [comment]
@hu5970 The regression test run on Jet with Intel compiler is successful at /mnt/lfs4/BMC/gsd-fv3-dev/Haiqin.Li/Commit2/ufs-weather-model/tests/RegressionTests_jet.intel.log, and the regression test run with GNU is successful at /scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS_dev/coarsepm.ufs-weather-model/tests/RegressionTests_hera.gnu.log.

**Comment by hu5970** [comment]
@haiqinli That is great, I will check the results and start merge the PR tomorrow. If everything works, we can update Hash in the APP tomorrow and deploy the new system.

**Comment by hu5970** [comment]
@haiqinli Could you commit three regression test logs to this PR? Thanks, Ming

**Comment by haiqinli** [comment]
@hu5970 The two log files of GNU and Jet.Intel have been committed. Thanks.

**Pull request merged**
