### PR TITLE
Update gsd/develop from develop 2020/10/01

### PR DESCRIPTION
**Pull request by climbfuji**
Changes in this PR:

- CCPP dependencies in `.meta` files
- update to two-way WW3-atmosphere coupling and fractional grid updates from Moorthi
- land surface perturbation updates
- diagnostic 3d instantaneous cloud fractions
- update to ESMF 8.1.0 bs27 with parallel netCDF
- cleanup/removal of legacy code, minor bugfixes
- cleanup of regression testing scripts
- removal of gnumake-based compile.sh, move `tests/compile_cmake.sh` to `tests/compile.sh` and remove first argument

Associated PRs:

https://github.com/NOAA-GSD/GFDL_atmos_cubed_sphere/pull/8
https://github.com/NOAA-GSD/ccpp-framework/pull/8
https://github.com/NOAA-GSD/ccpp-physics/pull/53
https://github.com/NOAA-GSD/fv3atm/pull/49
https://github.com/NOAA-GSD/ufs-weather-model/pull/41

For regression testing information, see below.

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
This PR is on hold until the global restart reproducibility issues have been fixed.

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf`: first create new baseline (to verify that all tests run to completion), then verify against it (to ensure that changing the MPI decomposition, changing the number of threads, and restart runs give b4b identical results): all tests pass.

[rt_ccpp_gsd_hera_intel_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5315571/rt_ccpp_gsd_hera_intel_create.log)
[rt_ccpp_gsd_hera_intel_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5315572/rt_ccpp_gsd_hera_intel_verify.log)

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel against official baseline using `rt.conf`: the following tests fail as expected (due to changes to GSL physics that have not been merged back to the official baseline), but run to completion. All other tests pass.
```
fv3_ccpp_rap 040 failed in check_result
fv3_ccpp_hrrr 041 failed in check_result
fv3_ccpp_thompson_no_aero 043 failed in check_result
fv3_ccpp_thompson 042 failed in check_result
fv3_ccpp_gsd 039 failed in check_result
fv3_ccpp_rrfs_v1beta 044 failed in check_result
fv3_ccpp_gsd_debug 053 failed in check_result
fv3_ccpp_rrfs_v1beta_debug 057 failed in check_result
fv3_ccpp_gsd_diag3d_debug 054 failed in check_result
fv3_ccpp_thompson_debug 055 failed in check_result
fv3_ccpp_thompson_no_aero_debug 056 failed in check_result
```

**Comment by DomHeinzeller** [comment]
Regression testing on hera.gnu against official baseline using `rt_gnu.conf`: the following tests fail as expected (due to changes to GSL physics that have not been merged back to the official baseline), but run to completion. All other tests pass.
```
fv3_ccpp_thompson 006 failed in check_result
fv3_ccpp_thompson_no_aero 007 failed in check_result
fv3_ccpp_rrfs_v1beta 008 failed in check_result
fv3_ccpp_gsd 005 failed in check_result
```

**Comment by DomHeinzeller** [comment]
@tanyasmirnova I think all five PRs are ready to merge. Please have a close look at the changes in https://github.com/NOAA-GSD/ccpp-physics/pull/53 for `module_mp_thompson.F90`. Thanks!

**Comment by tanyasmirnova** [comment]
@DomHeinzeller I checked module_mp_thompson.F90 - all changes look good.

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
