### PR TITLE
Update submodule pointer for FV3 (CCPP/Thompson initialization update)

### PR DESCRIPTION
**Pull request by climbfuji**
Update submodule pointer for FV3 and .gitmodules for code review process for PRs https://github.com/NOAA-GSD/fv3atm/pull/5 and https://github.com/NOAA-GSD/ccpp-physics/pull/4

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
@grantfirl @llpcarson you can't be reviewers for the NOAA-GSD GitHub website, but I would like to have your eyes on this PR to gsd/develop.

**Comment by DomHeinzeller** [comment]
@tanyasmirnova @joeolson42 @haiqinli @hannahcbarnes you can't be reviewers for the NOAA-GSD GitHub website, but I would like to have your eyes on this PR to gsd/develop.

I would like to ask someone to test this version, too. Maybe run the 10 test cases? You can check out the code as follows:
```
git clone https://github.com/NOAA-GSD/ufs-weather-model ufs-weather-model-gsd-develop-rearrange-ccpp-and-thompson-init
cd ufs-weather-model-gsd-develop-rearrange-ccpp-and-thompson-init
git fetch origin pull/3/head:gsd-develop-rearrange-ccpp-and-thompson-init
git checkout gsd-develop-rearrange-ccpp-and-thompson-init
git submodule sync
git submodule update --init --recursive
```

**Comment by climbfuji** [comment]
I did a manual comparison of the fv3_ccpp_thompson regression test between the old version and the new version. After moving the init code, fixing the number concentrations (convert from moist to dry and back), and calculating the effective radii, I get these differences between what the Thompson init "sees" and calculates between the original code and this code (example data for the MPI task zero, values are min/mean/max for the arrays:
```
thompson init OLD: phil  :   214.897049866277         138835.738282287         544025.207993417     
thompson init OLD: prsl  :   37.9138073076709         39710.0478281479         102687.555514823     
thompson init OLD: hgt   :   21.9134005869769         14157.3053267208         55475.1324859577     
thompson init OLD: rho   :   5.148312887097816E-004   0.518983001713771        1.26366344125984     
thompson init OLD: orho  :   0.791349949162908        68.6512334419160         1942.38388755683     
thompson init OLD: qv    :   4.769529168939579E-007   1.538391315611973E-003   1.208700947187085E-002
thompson init OLD: qc    :   4.898585674633937E-109   5.102116956060724E-006   5.068465950051689E-004
thompson init OLD: qr    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init OLD: qi    :   4.069717296105470E-043   3.060604107999084E-006   7.549271833102553E-004
thompson init OLD: qs    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init OLD: qg    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init OLD: ni    :   3.342936810312659E-035   47189.5637715245         17542704.4140853     
thompson init OLD: nr    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init OLD: nc    :   0.000000000000000E+000   131083.523236938         18205093.6712610     
thompson init OLD: nwfa  :   192399325.581717         1018597532.68146         8599647300.03527     
thompson init OLD: nifa  :   1.878097124601308E-005   181610.815532806         934786.155129273     
thompson init OLD: nwfa2d:   49046.7187067334         214475.299455592         1271518.80980218     
thompson init OLD: nifa2d:   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000

thompson init NEW: phil  :   214.817690966530         138563.833720646         541963.635501525     
thompson init NEW: prsl  :   37.9170142799696         39857.3750923145         102687.555514823     
thompson init NEW: hgt   :   21.9053082313053         14129.5787777320         55264.9105965365     
thompson init NEW: rho   :   5.146636767293567E-004   0.524549905438679        1.26412823730697     
thompson init NEW: orho  :   0.791058984751692        68.4554142035332         1943.01646923077     
thompson init NEW: qv    :   1.258373691318526E-006   1.308232623303572E-003   7.985285911597527E-003
thompson init NEW: qc    :   0.000000000000000E+000   5.169804308583890E-006   5.120899604440720E-004
thompson init NEW: qr    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init NEW: qi    :   0.000000000000000E+000   1.114588579583464E-006   1.206990567083932E-004
thompson init NEW: qs    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init NEW: qg    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init NEW: ni    :   0.000000000000000E+000   8978.70906479792         1960916.22482433     
thompson init NEW: nr    :   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000
thompson init NEW: nc    :   0.000000000000000E+000   518644.118743558         50746169.8571715     
thompson init NEW: nwfa  :   223328901.989270         734568880.102218         3258335008.39060     
thompson init NEW: nifa  :   1.878097107864000E-005   204854.084364571         718144.465947702     
thompson init NEW: nwfa2d:   47389.7960962146         105505.240445408         282942.864949380     
thompson init NEW: nifa2d:   0.000000000000000E+000   0.000000000000000E+000   0.000000000000000E+000

thompson init NEW: re_cloud: 2.490000000000000E-006   7.699852492353284E-006   1.421052631577410E-005
thompson init NEW: re_ice  : 4.990000000000000E-006   3.706072006919318E-005   1.250000000000000E-004
thompson init NEW: re_snow : 9.989999999999999E-006   9.990000000000140E-006   9.989999999999999E-006
```

**Comment by climbfuji** [comment]
After updating GFS_rrtmg_pre (turn off the effective radii initialization to default values for Thompson MP), I ran the 24h regression tests and got these values (global, reported at end of run; here it is max/min/mean):
```
24h fcst OLD: ZS   5396.08251953125       -29.3378028869629        232.508666569163     
24h fcst OLD: PS    1040.26705431787        527.008973540236        985.655075921001     
24h fcst OLD: PS* max =   1040.26705431787       min =    527.008973540236     
24h fcst OLD: U  max =    86.2468366970578       min =   -95.1686071064353     
24h fcst OLD: V  max =    88.5157850183263       min =   -99.9903773236978     
24h fcst OLD: W  max =    0.874359254543872      min =  -0.317628257892810     
24h fcst OLD: T  max =    312.767080550766       min =    186.033717651516     
24h fcst OLD: sphum      2.127390247865357E-002   1.811455415891704E-008   9.463196861165047E-003
24h fcst OLD: liq_wat    9.157342308979492E-003   0.000000000000000E+000   9.796657168952383E-006
24h fcst OLD: ice_wat    2.537628133501687E-004   0.000000000000000E+000   6.305284174607135E-008
24h fcst OLD: rainwat    8.319008584880513E-003   0.000000000000000E+000   3.337096454649503E-006
24h fcst OLD: snowwat    4.978187720835580E-003   0.000000000000000E+000   2.794472746712719E-006
24h fcst OLD: graupel    2.412749417257972E-004   0.000000000000000E+000   3.346179967924981E-008
24h fcst OLD: water_nc   660960131.893066         0.000000000000000E+000   252728.036038218     
24h fcst OLD: ice_nc     2457066.93935436         0.000000000000000E+000   295.047120563093     
24h fcst OLD: rain_nc    1921253.33582909         0.000000000000000E+000   1682.28409453384     
24h fcst OLD: o3mr       1.898357617398259E-005   3.529132578712669E-008   5.825888684578628E-008
24h fcst OLD: liq_aero   54374801634.6434         11045421.6126881         3124363388.61338     
24h fcst OLD: ice_aero   53961095.0909947         4837.84642055852         1946549.09301356     

24h fcst NEW: ZS   5396.08251953125       -29.3378028869629        232.508666569163
24h fcst NEW: PS    1040.31883792951        527.011913692626        985.654855018724
24h fcst NEW: PS* max =   1040.31883792951       min =    527.011913692626
24h fcst NEW: U  max =    86.3249340547262       min =   -95.2350094896036
24h fcst NEW: V  max =    88.5795289577638       min =   -100.180365532399
24h fcst NEW: W  max =    0.889331054829374      min =  -0.315511539447094
24h fcst NEW: T  max =    312.619610235107       min =    185.584707129384
24h fcst NEW: sphum      2.128675680446777E-002   1.000002085864958E-009   9.462602024517264E-003
24h fcst NEW: liq_wat    7.355964389385261E-003   0.000000000000000E+000   7.937223430352016E-006
24h fcst NEW: ice_wat    2.781620730373264E-004   0.000000000000000E+000   6.403768161314911E-008
24h fcst NEW: rainwat    3.978653384152314E-003   0.000000000000000E+000   3.542641195637863E-006
24h fcst NEW: snowwat    3.742770453364911E-003   0.000000000000000E+000   2.830359856870431E-006
24h fcst NEW: graupel    1.475834704230070E-004   0.000000000000000E+000   3.036225355280129E-008
24h fcst NEW: water_nc   643334841.788210         0.000000000000000E+000   163274.739135477
24h fcst NEW: ice_nc     2427135.00469464         0.000000000000000E+000   308.278836972096
24h fcst NEW: rain_nc    1560537.15091487         0.000000000000000E+000   1727.04468672025
24h fcst NEW: o3mr       1.898328211648002E-005   3.528608686624434E-008   5.825759616832204E-008
24h fcst NEW: liq_aero   44891698103.0774         11059026.6614254         1734415889.36147
24h fcst NEW: ice_aero   53967973.2607781         4802.50996190014         1946697.37137188
```
These number show that the results are similar. This is of course not a scientific evaluation, hence my request for someone to run the ten test cases ...

**Comment by climbfuji** [comment]
@ligiabernardet @shansun adding you as well to take a look if you want

**Comment by tanyasmirnova** [comment]
Dom,
Thank you very much for making all this happen. I am very excited about testing all these changes, but am afraid that I will get to this only next year. 
Happy New Year!
Tanya

**Comment by hannahcbarnes** [comment]
Hi Dom,

I will also look at this later this week. I think Judy gets back next week.
I can talk to her about how I can use this updated code to run a 10 case
Retro.

Best
Hannah
-------------
Hannah C Barnes
Research Scientist I
University of Colorado Boulder
Cooperative Institute for Research in Environmental Sciences
NOAA/OAR/ESRL/GSD Model Development Branch

325 Broadway, Bldg. DSRC
Boulder, CO 80305-3328
(303) 497-6924
hannah.barnes@noaa.gov

**Comment by tanyasmirnova** [comment]
Dom,
I am getting very minor differences from these changes in the EMC+Thompson suite, and even smaller differences in EMC+MYNN suite.
The plot below shows the temperature differences in 18-h forecast at 950 mb level for EMC+Thomp: the run with proposed code changes minus the control run

Screen Shot 2020-01-03 at 3 20 15 PM

Similar minor differences at other levels and for other variables.
So - I have no objections against these modifications.
Thanks,
Tanya

**Review by tanyasmirnova — APPROVED** [review]

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
