### PR TITLE
"update .gitmodules to point to the gsl/develop-smoke"

### PR DESCRIPTION
**Pull request by haiqinli**
1). to include the smoke subroutines;
2). to update MYNN PBL transport, Thompson MP aerosol indirect feedback, radiation direct feedback;
3). Passed the regression test run case of rrfs_conus13km_hrrr_warm with Intel and GNU compiler on Hera;
The successful log files are at:
/scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS-Smoke/ufs-weather-model/tests/intel_out
/scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS-Smoke/ufs-weather-model/tests/gnu_out

4). Created a new regression test run case of /scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS-Smoke/ufs-weather-model/tests/tests/rrfs_smoke_conus13km_hrrr_warm. The meteorological fields are identical with rrfs_conus13km_hrrr_warm the when turning off direct/indirect aerosol feedback.

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
The tests fail because the FV3/ccpp/physics does not point to your ccpp-physics PR. Hence, the smoke directory is missing, along with all of your other ccpp-physics changes.

Also, you did not push the tests/tests/rrfs_smoke_conus13km_hrrr_warm file. It is not in this PR yet.

**Comment by haiqinli** [comment]
1).  Updated that FV3/ccpp/physics points to the gsl/develop-smoke cccp-physics PR.
2).  It is added. [push tests/tests/rrfs_smoke_conus13km_hrrr_warm"](https://github.com/NOAA-GSL/ufs-weather-model/pull/135/commits/fa8b182ac7a12a82e2fdf0138cca5cf28f56d20e)

**Comment by SamuelTrahanNOAA** [comment]
It does not compile for me.

```
/scratch2/BMC/wrfruc/Samuel.Trahan/gsl-PR/try2-pr135/FV3/ccpp/physics/physics/GFS_SCNV_generic.F90(216): error #6404: This name does not have a type, and must have an explicit type.   [GQ0_WATER_VAPOR]
            tem  = (gq0_water_vapor(i,k)-save_qv(i,k)) * frain
--------------------^
/scratch2/BMC/wrfruc/Samuel.Trahan/gsl-PR/try2-pr135/FV3/ccpp/physics/physics/GFS_SCNV_generic.F90(216): error #6404: This name does not have a type, and must have an explicit type.   [SAVE_QV]
            tem  = (gq0_water_vapor(i,k)-save_qv(i,k)) * frain
-----------------------------------------^
```

**Comment by SamuelTrahanNOAA** [comment]
>  Updated that FV3/ccpp/physics points to the gsl/develop-smoke cccp-physics PR.

No, you did not. I just updated the submodule hashes for you, but it still won't compile.

**Comment by SamuelTrahanNOAA** [comment]
Most of the configurations fail to build due to two undefined variables in GFS_SCNV_generic.F90: save_qv and g10_water_vapor.

**Comment by haiqinli** [comment]
The Hera.Intel regression test run is successful at /scratch2/BMC/acomp/Haiqin.Li/Commit/RRFS-Smoke/ufs-weather-model/tests/RegressionTests_hera.intel.log.

**Comment by haiqinli** [comment]
The Hera.GNU regression test is also successful at /scratch2/BMC/acomp/Haiqin.Li/Commit/ufs-weather-model/tests/RegressionTests_hera.gnu.log.

**Review by SamuelTrahanNOAA — APPROVED** [review]

**Pull request merged**
