### PR TITLE
Make changes for automated regression testing, Issue #159, PR

### PR DESCRIPTION
**Pull request by venitahagerty**
Labels will be added, and other actions taken, to change state that will trigger regression testing. This is part of the RRFS CI project.

### CODE REVIEW

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20221213223959/ufs-weather-model
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230124201753/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_85713
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230126184553/ufs-weather-model
/scratch1/BMC/zrtrr/rrfs_ci/wxmodel/RT/develop-20220630/INTEL
 Exists already. It should not yet. Please delete.
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230126204756/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_209336
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230127142356/ufs-weather-model
/scratch1/BMC/zrtrr/rrfs_ci/wxmodel/RT/develop-20220630/INTEL
 Exists already. It should not yet. Please delete.
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230127143237/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_308955
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230201143252/ufs-weather-model
/scratch1/BMC/zrtrr/rrfs_ci/wxmodel/RT/develop-20220630/INTEL
 Exists already. It should not yet. Please delete.
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230201151542/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_276891
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230202165304/ufs-weather-model
/scratch1/BMC/zrtrr/rrfs_ci/wxmodel/RT/develop-20220630/INTEL
 Exists already. It should not yet. Please delete.
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230202165923/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_224464
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230202183844/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_53644
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230202194631/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_266217
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230202211034/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_254685
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230209004231/ufs-weather-model
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230209005455/ufs-weather-model
Please manually delete: /scratch2/BMC/gsd-hpcs/Jacques.Middlecoff/stmp/stmp2/Jacques.Middlecoff/FV3_RT/rt_245647
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230209140038/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_122256
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230227163642/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_277002
Regression test successful
Please obtain logs from /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230227163642/ufs-weather-model
If test failed, please make changes and add the following label back:
ci-hera-intel-RT

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230228165311/ufs-weather-model
Please manually delete: /lfs4/HFIP/hfv3gfs/Samuel.Trahan/RT_RUNDIRS/Samuel.Trahan/FV3_RT/rt_101323
Test regional_debug 080 failed in run_test failed 
Test rap_control_debug 081 failed in run_test failed 
If test failed, please make changes and add the following label back:
ci-jet-intel-BL

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230228175543/ufs-weather-model
If test failed, please make changes and add the following label back:
ci-jet-intel-BL

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230228230145/ufs-weather-model
If test failed, please make changes and add the following label back:
ci-jet-intel-BL

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230301134556/ufs-weather-model
/lfs1/BMC/nrtrr/rrfs_ci/wxmodel/RT/NEMSfv3gfs/gsl-develop-20220630/INTEL
 Exists already. It should not yet. Please delete.
If test failed, please make changes and add the following label back:
ci-jet-intel-BL

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230301200502/ufs-weather-model
Please manually delete: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_8814
Regression test successful
If test failed, please make changes and add the following label back:
ci-jet-intel-RT

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: BL
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230302134053/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_3336
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-hera-intel-BL

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: BL
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230302134852/ufs-weather-model
Please manually delete: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_295657
Baseline creation and move successful
If test failed, please make changes and add the following label back:
ci-jet-intel-BL

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: RT
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/pr/1161740689/20230302170542/ufs-weather-model
Please manually delete: /scratch1/BMC/zrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_31914
Regression test successful
If test failed, please make changes and add the following label back:
ci-hera-intel-RT

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230302170554/ufs-weather-model
Please manually delete: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_210444
Regression test successful
If test failed, please make changes and add the following label back:
ci-jet-intel-RT

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: RT
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/pr/1161740689/20230306221457/ufs-weather-model
Please manually delete: /lfs1/BMC/nrtrr/rrfs_ci/wxmodel/stmp2/rtrr/FV3_RT/rt_184596
Regression test successful
If test failed, please make changes and add the following label back:
ci-jet-intel-RT

**Comment by middlecoff** [comment]
Hi Venita,

I looked at this but I don't feel qualified to approve ti.

Jacques

**Review by christinaholtNOAA — APPROVED** [review]
LGTM!

And it seems that all the tests pass for hera and jet intel!

**Pull request merged**
