### PR TITLE
Add drag suite and other updates

### PR DESCRIPTION
**Pull request by climbfuji**
Changes in this PR:
- drag suite update from @mdtoy (https://github.com/NOAA-GSD/ufs-weather-model/pull/19), with updates to address review comments
- rename regression test fv3_ccpp_raphrrr to fv3_ccpp_hrrr (to match the renaming of suite FV3_RAPHRRR to FV3_HRRR in https://github.com/NOAA-GSD/fv3atm/pull/32)
- add regression test fv3_ccpp_rap

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/32
https://github.com/NOAA-GSD/fv3atm/pull/32
https://github.com/NOAA-GSD/ufs-weather-model/pull/25

For regression testing information, see below **NOT YET**.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing on hera.intel against existing EMC baseline. As expected, and as with previous commits, the following tests fail (missing baseline or different results), all others pass:
```
fv3_ccpp_thompson_no_aero
fv3_ccpp_thompson
fv3_ccpp_gsd
fv3_ccpp_thompson_no_aero_debug
fv3_ccpp_gsd_debug
fv3_ccpp_thompson_debug
```
[rt_full.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4732327/rt_full.log)
[rt_full_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4732328/rt_full_fail_test.log)

**Comment by climbfuji** [comment]
@tanyasmirnova @mdtoy @joeolson42 @hannahcbarnes @haiqinli please review this PR and PRs listed in here. Basically Mike's changes with a little cleanup from my side (only in the ufs-weather-model), and some additional updates to address open issues in ccpp-physics and fv3atm. Thanks!

**Comment by climbfuji** [comment]
Regression testing on hera.intel against existing/old GSD baseline. As expected, the following tests fail, all others pass:
```
fv3_ccpp_gsd_drag_suite # updates to drag suite
fv3_ccpp_rap # new test
fv3_ccpp_hrrr # switched from CIRES UGWP to drag suite
```
[rt_ccpp_gsd_verify_against_old_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4733558/rt_ccpp_gsd_verify_against_old_baseline.log)
[rt_ccpp_gsd_verify_against_old_baseline_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4733560/rt_ccpp_gsd_verify_against_old_baseline_fail_test.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf`: first create a baseline (to make sure all tests complete successfully), then verify against it (to check run-to-run reproducibility, restarts etc): all tests pass. Code is ready to merge.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4733567/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4733568/rt_ccpp_gsd_verify.log)

**Review by DomHeinzeller — APPROVED** [review]
Most code changes are from @mdtoy. Approved by @tanyasmirnova and myself.

**Pull request merged**
