### PR TITLE
gsd/develop: update from NOAA-EMC develop

### PR DESCRIPTION
**Pull request by climbfuji**
This PR updates the NOAA-GSD gsd/develop branch of ufs-weather-model with the latest version from NOAA-EMC (ufs-community) develop.

Associated PRs:

https://github.com/NOAA-GSD/GFDL_atmos_cubed_sphere/pull/2
https://github.com/NOAA-GSD/ccpp-framework/pull/3
https://github.com/NOAA-GSD/ccpp-physics/pull/28
https://github.com/NOAA-GSD/fv3atm/pull/28
https://github.com/NOAA-GSD/ufs-weather-model/pull/22

See below for regression testing information.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing on hera.intel against official EMC baseline using `rt.conf`. 
All tests pass except those expected to fail (because of our updates to Thompson MP and other physics used in the GSD suite).

[rt_full_hera_intel.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4636602/rt_full_hera_intel.log)

```
bash-4.2$ grep -e FAIL log_hera.intel/*
log_hera.intel/rt_036_fv3_ccpp_gsd_prod.log:Test 036 fv3_ccpp_gsd FAIL
log_hera.intel/rt_037_fv3_ccpp_thompson_prod.log:Test 037 fv3_ccpp_thompson FAIL
log_hera.intel/rt_038_fv3_ccpp_thompson_no_aero_prod.log:Test 038 fv3_ccpp_thompson_no_aero FAIL
log_hera.intel/rt_045_fv3_ccpp_gsd_debug_prod.log:Test 045 fv3_ccpp_gsd_debug FAIL
log_hera.intel/rt_046_fv3_ccpp_thompson_debug_prod.log:Test 046 fv3_ccpp_thompson_debug FAIL
log_hera.intel/rt_047_fv3_ccpp_thompson_no_aero_debug_prod.log:Test 047 fv3_ccpp_thompson_no_aero_debug FAIL
bash-4.2$ grep -e PASS log_hera.intel/*
log_hera.intel/rt_001_fv3_ccpp_control_prod.log:Test 001 fv3_ccpp_control PASS
log_hera.intel/rt_002_fv3_ccpp_decomp_prod.log:Test 002 fv3_ccpp_decomp PASS
log_hera.intel/rt_003_fv3_ccpp_2threads_prod.log:Test 003 fv3_ccpp_2threads PASS
log_hera.intel/rt_004_fv3_ccpp_restart_prod.log:Test 004 fv3_ccpp_restart PASS
log_hera.intel/rt_005_fv3_ccpp_read_inc_prod.log:Test 005 fv3_ccpp_read_inc PASS
log_hera.intel/rt_006_fv3_ccpp_wrtGauss_netcdf_esmf_prod.log:Test 006 fv3_ccpp_wrtGauss_netcdf_esmf PASS
log_hera.intel/rt_007_fv3_ccpp_wrtGauss_netcdf_prod.log:Test 007 fv3_ccpp_wrtGauss_netcdf PASS
log_hera.intel/rt_008_fv3_ccpp_wrtGlatlon_netcdf_prod.log:Test 008 fv3_ccpp_wrtGlatlon_netcdf PASS
log_hera.intel/rt_009_fv3_ccpp_wrtGauss_nemsio_prod.log:Test 009 fv3_ccpp_wrtGauss_nemsio PASS
log_hera.intel/rt_010_fv3_ccpp_wrtGauss_nemsio_c192_prod.log:Test 010 fv3_ccpp_wrtGauss_nemsio_c192 PASS
log_hera.intel/rt_011_fv3_ccpp_stochy_prod.log:Test 011 fv3_ccpp_stochy PASS
log_hera.intel/rt_012_fv3_ccpp_iau_prod.log:Test 012 fv3_ccpp_iau PASS
log_hera.intel/rt_013_fv3_ccpp_ca_prod.log:Test 013 fv3_ccpp_ca PASS
log_hera.intel/rt_014_fv3_ccpp_lheatstrg_prod.log:Test 014 fv3_ccpp_lheatstrg PASS
log_hera.intel/rt_015_fv3_ccpp_gfdlmprad_prod.log:Test 015 fv3_ccpp_gfdlmprad PASS
log_hera.intel/rt_016_fv3_ccpp_gfdlmprad_atmwav_prod.log:Test 016 fv3_ccpp_gfdlmprad_atmwav PASS
log_hera.intel/rt_017_fv3_ccpp_wrtGauss_nemsio_c768_prod.log:Test 017 fv3_ccpp_wrtGauss_nemsio_c768 PASS
log_hera.intel/rt_018_fv3_ccpp_control_32bit_prod.log:Test 018 fv3_ccpp_control_32bit PASS
log_hera.intel/rt_019_fv3_ccpp_stretched_prod.log:Test 019 fv3_ccpp_stretched PASS
log_hera.intel/rt_020_fv3_ccpp_stretched_nest_prod.log:Test 020 fv3_ccpp_stretched_nest PASS
log_hera.intel/rt_021_fv3_ccpp_regional_control_prod.log:Test 021 fv3_ccpp_regional_control PASS
log_hera.intel/rt_022_fv3_ccpp_regional_restart_prod.log:Test 022 fv3_ccpp_regional_restart PASS
log_hera.intel/rt_023_fv3_ccpp_regional_quilt_prod.log:Test 023 fv3_ccpp_regional_quilt PASS
log_hera.intel/rt_024_fv3_ccpp_regional_c768_prod.log:Test 024 fv3_ccpp_regional_c768 PASS
log_hera.intel/rt_025_fv3_ccpp_control_debug_prod.log:Test 025 fv3_ccpp_control_debug PASS
log_hera.intel/rt_026_fv3_ccpp_stretched_nest_debug_prod.log:Test 026 fv3_ccpp_stretched_nest_debug PASS
log_hera.intel/rt_027_fv3_ccpp_gfdlmp_prod.log:Test 027 fv3_ccpp_gfdlmp PASS
log_hera.intel/rt_028_fv3_ccpp_gfdlmprad_gwd_prod.log:Test 028 fv3_ccpp_gfdlmprad_gwd PASS
log_hera.intel/rt_029_fv3_ccpp_gfdlmprad_noahmp_prod.log:Test 029 fv3_ccpp_gfdlmprad_noahmp PASS
log_hera.intel/rt_030_fv3_ccpp_csawmg_prod.log:Test 030 fv3_ccpp_csawmg PASS
log_hera.intel/rt_031_fv3_ccpp_satmedmf_prod.log:Test 031 fv3_ccpp_satmedmf PASS
log_hera.intel/rt_032_fv3_ccpp_satmedmfq_prod.log:Test 032 fv3_ccpp_satmedmfq PASS
log_hera.intel/rt_033_fv3_ccpp_gfdlmp_32bit_prod.log:Test 033 fv3_ccpp_gfdlmp_32bit PASS
log_hera.intel/rt_034_fv3_ccpp_gfdlmprad_32bit_post_prod.log:Test 034 fv3_ccpp_gfdlmprad_32bit_post PASS
log_hera.intel/rt_035_fv3_ccpp_cpt_prod.log:Test 035 fv3_ccpp_cpt PASS
log_hera.intel/rt_039_fv3_ccpp_gfs_v15p2_prod.log:Test 039 fv3_ccpp_gfs_v15p2 PASS
log_hera.intel/rt_040_fv3_ccpp_gfs_v16beta_prod.log:Test 040 fv3_ccpp_gfs_v16beta PASS
log_hera.intel/rt_041_fv3_ccpp_rrtmgp_prod.log:Test 041 fv3_ccpp_rrtmgp PASS
log_hera.intel/rt_042_fv3_ccpp_gfs_v15p2_debug_prod.log:Test 042 fv3_ccpp_gfs_v15p2_debug PASS
log_hera.intel/rt_043_fv3_ccpp_gfs_v16beta_debug_prod.log:Test 043 fv3_ccpp_gfs_v16beta_debug PASS
log_hera.intel/rt_044_fv3_ccpp_rrtmgp_debug_prod.log:Test 044 fv3_ccpp_rrtmgp_debug PASS
log_hera.intel/rt_048_fv3_ccpp_gfsv16_csawmg_prod.log:Test 048 fv3_ccpp_gfsv16_csawmg PASS
log_hera.intel/rt_049_fv3_ccpp_gfsv16_csawmgt_prod.log:Test 049 fv3_ccpp_gfsv16_csawmgt PASS
log_hera.intel/rt_050_fv3_ccpp_gocart_clm_prod.log:Test 050 fv3_ccpp_gocart_clm PASS
```

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf` against previous GSD baseline (created from the head of gsd/develop): all tests fail. This is expected because of the changes merged from the authoritative repository. 

[rt_ccpp_gsd_against_existing_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4637041/rt_ccpp_gsd_against_existing_baseline.log)

```
bash-4.2$ grep -e FAIL log_hera.intel/*
log_hera.intel/rt_001_fv3_ccpp_thompson_mynn_repro.log:Test 001 fv3_ccpp_thompson_mynn FAIL
log_hera.intel/rt_002_fv3_ccpp_gf_thompson_repro.log:Test 002 fv3_ccpp_gf_thompson FAIL
log_hera.intel/rt_003_fv3_ccpp_gsd_repro.log:Test 003 fv3_ccpp_gsd FAIL
log_hera.intel/rt_004_fv3_ccpp_gsd_coldstart_repro.log:Test 004 fv3_ccpp_gsd_coldstart FAIL
log_hera.intel/rt_005_fv3_ccpp_gsd_warmstart_repro.log:Test 005 fv3_ccpp_gsd_warmstart FAIL
log_hera.intel/rt_006_fv3_ccpp_gsd_noah_repro.log:Test 006 fv3_ccpp_gsd_noah FAIL
log_hera.intel/rt_007_fv3_ccpp_gsd_mynnsfc_repro.log:Test 007 fv3_ccpp_gsd_mynnsfc FAIL
log_hera.intel/rt_008_fv3_ccpp_gsd_noah_mynnsfc_repro.log:Test 008 fv3_ccpp_gsd_noah_mynnsfc FAIL
log_hera.intel/rt_009_fv3_ccpp_thompson_repro.log:Test 009 fv3_ccpp_thompson FAIL
log_hera.intel/rt_010_fv3_ccpp_thompson_no_aero_repro.log:Test 010 fv3_ccpp_thompson_no_aero FAIL
log_hera.intel/rt_011_fv3_ccpp_gf_repro.log:Test 011 fv3_ccpp_gf FAIL
log_hera.intel/rt_012_fv3_ccpp_mynn_repro.log:Test 012 fv3_ccpp_mynn FAIL
log_hera.intel/rt_013_fv3_ccpp_gsd_drag_suite_repro.log:Test 013 fv3_ccpp_gsd_drag_suite FAIL
log_hera.intel/rt_014_fv3_ccpp_gsd_sar_repro.log:Test 014 fv3_ccpp_gsd_sar FAIL
log_hera.intel/rt_015_fv3_ccpp_gsd_debug_prod.log:Test 015 fv3_ccpp_gsd_debug FAIL
log_hera.intel/rt_016_fv3_ccpp_gsd_diag3d_debug_prod.log:Test 016 fv3_ccpp_gsd_diag3d_debug FAIL
log_hera.intel/rt_017_fv3_ccpp_gsd_mynnsfc_debug_prod.log:Test 017 fv3_ccpp_gsd_mynnsfc_debug FAIL
log_hera.intel/rt_018_fv3_ccpp_gsd_noah_mynnsfc_debug_prod.log:Test 018 fv3_ccpp_gsd_noah_mynnsfc_debug FAIL
log_hera.intel/rt_019_fv3_ccpp_thompson_no_aero_debug_prod.log:Test 019 fv3_ccpp_thompson_no_aero_debug FAIL
log_hera.intel/rt_020_fv3_ccpp_gsd_sar_25km_debug_prod.log:Test 020 fv3_ccpp_gsd_sar_25km_debug FAIL
bash-4.2$ grep -e PASS log_hera.intel/*
bash-4.2$
```

**Comment by climbfuji** [comment]
Regression testing on hera.intel using rt_ccpp_gsd.conf: first create new baseline, then verify against it: all tests pass.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4637483/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4637484/rt_ccpp_gsd_verify.log)

**Comment by climbfuji** [comment]
These PRs are ready to merge pending code review and testing by the GSL physics developers.

@haiqinli @hannahcbarnes @joeolson42 @tanyasmirnova @shansun6

**Comment by climbfuji** [comment]
@haiqinli @hannahcbarnes @joeolson42 @tanyasmirnova see commit https://github.com/NOAA-GSD/ufs-weather-model/pull/22/commits/bd1c7c9776862ce9c2020ce6269d13da58115028 for the new regression test fv3_ccpp_raphrrr. Note the "inconsistency" of running the RAP-HRRR suite with a C96 global configuration in the regression tests, but running the full 3km SAR domain takes way too long for regression tests. And the main point here is to make sure the suite runs to completion and to catch unintended changes in following commits. In future commits, I will add  restart an debug tests.

**Comment by climbfuji** [comment]
Regression testing of updated version of the code (after commits https://github.com/NOAA-GSD/ccpp-physics/commit/6e4c7874d6685953b8887fd7638fdfb8870c4b2d, https://github.com/NOAA-GSD/fv3atm/commit/dabf9e6bb034334f087ad93c6c171e130934f5dc, https://github.com/NOAA-GSD/ufs-weather-model/commit/bd1c7c9776862ce9c2020ce6269d13da58115028) on hera.intel against official EMC baseline: all tests pass except those expected to fail:
```
log_hera.intel/rt_036_fv3_ccpp_gsd_prod.log:Test 036 fv3_ccpp_gsd FAIL
log_hera.intel/rt_037_fv3_ccpp_thompson_prod.log:Test 037 fv3_ccpp_thompson FAIL
log_hera.intel/rt_038_fv3_ccpp_thompson_no_aero_prod.log:Test 038 fv3_ccpp_thompson_no_aero FAIL
log_hera.intel/rt_045_fv3_ccpp_gsd_debug_prod.log:Test 045 fv3_ccpp_gsd_debug FAIL
log_hera.intel/rt_046_fv3_ccpp_thompson_debug_prod.log:Test 046 fv3_ccpp_thompson_debug FAIL
log_hera.intel/rt_047_fv3_ccpp_thompson_no_aero_debug_prod.log:Test 047 fv3_ccpp_thompson_no_aero_debug FAIL
```

[rt_full_hera_intel.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4650743/rt_full_hera_intel.log)
[rt_full_hera_intel_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4650747/rt_full_hera_intel_fail_test.log)

**Comment by climbfuji** [comment]
Regression testing of updated version of the code (after commits https://github.com/NOAA-GSD/ccpp-physics/commit/6e4c7874d6685953b8887fd7638fdfb8870c4b2d, https://github.com/NOAA-GSD/fv3atm/commit/dabf9e6bb034334f087ad93c6c171e130934f5dc, https://github.com/NOAA-GSD/ufs-weather-model/commit/bd1c7c9776862ce9c2020ce6269d13da58115028) on hera.intel using `rt_ccpp_gsd.conf`: first create new baseline, then verify against it: all tests pass.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4650843/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4650844/rt_ccpp_gsd_verify.log)

**Comment by climbfuji** [comment]
@haiqinli @hannahcbarnes @joeolson42 @tanyasmirnova all tests pass as expected. Please let me know if you are happy with the PRs and I will start the merge process. Thanks!

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
