### PR TITLE
gsd/develop: update from from develop 2020/01/27

### PR DESCRIPTION
**Pull request by climbfuji**
Update gsd/develop from develop:
- inline post changes
- GFSv16 changes
- cmake build system changes
- updates from dtc/develop that were merged to develop previously
- replace GFS_v15 and GFS_v15plus tests with GFS_v15p2 and GFS_v16beta tests

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Associated PRs:
https://github.com/NOAA-GSD/ufs-weather-model/pull/7
https://github.com/NOAA-GSD/fv3atm/pull/9
https://github.com/NOAA-GSD/GFDL_atmos_cubed_sphere/pull/1
https://github.com/NOAA-GSD/ccpp-physics/pull/9
https://github.com/NOAA-GSD/ccpp-framework/pull/2

**Comment by climbfuji** [comment]
@tanyasmirnova @haiqinli @joeolson42 can you please have a look at this PR and associated PRs? I will update the regression testing info in a few minutes (all looking good). Thanks!

**Comment by tanyasmirnova** [comment]
Dom,
I think the last part of the following code in the GFS_MP_generic.F90 could be also done for RUC in case dtf /= dtp:
if (lsm==lsm_ruc) then
        if (imp_physics == imp_physics_gfdl .or. imp_physics == imp_physics_thompson) then

      if (lsm==lsm_ruc .or. lsm==lsm_noahmp) then
            raincprv(:)   = rainc(:)
            rainncprv(:)  = frain * rain1(:)
            iceprv(:)     = ice(:)
            snowprv(:)    = snow(:)
            graupelprv(:) = graupel(:)
        !for NoahMP, calculate precipitation rates from liquid water equivalent thickness for use in next time step
        !Note (GJF): Precipitation LWE thicknesses are multiplied by the frain factor, and are thus on the dynamics time step, but the conversion as written
        !            (with dtp in the denominator) assumes the rate is calculated on the physics time step. This only works as expected when dtf=dtp (i.e. when frain=1).
        if (lsm == lsm_noahmp) then
          tem = 1.0 / (dtp*con_p001) !GJF: This conversion was taken from GFS_physics_driver.F90, but should denominator also have the frain factor?
          draincprv(:)   = tem * raincprv(:)
          drainncprv(:)  = tem * rainncprv(:)
          dsnowprv(:)    = tem * snowprv(:)
          dgraupelprv(:) = tem * graupelprv(:)
          diceprv(:)     = tem * iceprv(:)
        end if
      end if

What do you think?
Thanks,
Tanya

**Comment by DomHeinzeller** [comment]
Ok, this will have to be a follow-up change. Can you create an issue for it, please?

**Comment by tanyasmirnova** [comment]
Dom,
I think I made a new issue for this.
Thanks,
Tanya

**Comment by DomHeinzeller** [comment]
> Dom,
> I think I made a new issue for this.
> Thanks,
> Tanya

Thank you, you did. I just transferred it from ufs-weather-model to ccpp-physics: https://github.com/NOAA-GSD/ccpp-physics/issues/11

**Comment by climbfuji** [comment]
Regression testing on hera.intel: run IPD PROD tests in rt.conf against EMC baseline - all pass.

[rt_ipd_prod_only.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134804/rt_ipd_prod_only.log)

Next, create full baseline for rt.conf (IPD PROD, IPD REPRO, CCPP PROD) and verify against it (IPD PROD, IPD REPRO, CCPPREPRO, CCPP PROD) - all pass.

[rt_full_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134805/rt_full_create.log)
[rt_full_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134806/rt_full_verify.log)

No need move the full baseline to the official DTC baseline directory, this was done by https://github.com/NCAR/ufs-weather-model/pull/20.

**Comment by climbfuji** [comment]
Regression testing on hera.intel for rt_ccpp_dtc.conf and rt_ccpp_gsd.conf, rt_ccpp_caps.conf (first create, then verify): all pass.

[rt_ccpp_dtc_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134813/rt_ccpp_dtc_create.log)
[rt_ccpp_dtc_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134814/rt_ccpp_dtc_verify.log)
[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134815/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4134816/rt_ccpp_gsd_verify.log)

**Comment by climbfuji** [comment]
This PR is ready to merge.

**Review by DomHeinzeller — APPROVED** [review]
Reviewed and approved by @haiqinli and @tanyasmirnova. All tests pass.

**Pull request merged**
