### PR TITLE
Number concentration bug and code clean up in ccpp-physics GFS_suite_interstitial_4

### PR DESCRIPTION
**Pull request by climbfuji**
Update .gitmodules and submodule pointer for fv3atm for code review and testing.

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/26/files
https://github.com/NOAA-GSD/fv3atm/pull/27
https://github.com/NOAA-GSD/ufs-weather-model/pull/21

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf` against existing codebase (i.e. generate baseline with current gsd/develop branch, then verify against it with the code in these PRs). All tests that use Thompson MP fail because of b4b mismatches (but they run to completion):
```
[Dom.Heinzeller@hfe04 tests]$ grep -e PASS log_hera.intel/*
log_hera.intel/rt_011_fv3_ccpp_gf_repro.log:Test 011 fv3_ccpp_gf PASS
log_hera.intel/rt_012_fv3_ccpp_mynn_repro.log:Test 012 fv3_ccpp_mynn PASS
[Dom.Heinzeller@hfe04 tests]$ grep -e FAIL log_hera.intel/*
log_hera.intel/rt_001_fv3_ccpp_thompson_mynn_repro.log:Test 001 fv3_ccpp_thompson_mynn FAIL
log_hera.intel/rt_002_fv3_ccpp_gf_thompson_repro.log:Test 002 fv3_ccpp_gf_thompson FAIL
log_hera.intel/rt_003_fv3_ccpp_gsd_repro.log:Test 003 fv3_ccpp_gsd FAIL
log_hera.intel/rt_004_fv3_ccpp_gsd_coldstart_repro.log:Test 004 fv3_ccpp_gsd_coldstart FAIL
log_hera.intel/rt_005_fv3_ccpp_gsd_warmstart_repro.log:Test 005 fv3_ccpp_gsd_warmstart FAIL
log_hera.intel/rt_006_fv3_ccpp_gsd_noah_repro.log:Test 006 fv3_ccpp_gsd_noah FAIL
log_hera.intel/rt_007_fv3_ccpp_gsd_mynnsfc_repro.log:Test 007 fv3_ccpp_gsd_mynnsfc FAIL
log_hera.intel/rt_008_fv3_ccpp_gsd_noah_mynnsfc_repro.log:Test 008 fv3_ccpp_gsd_noah_mynnsfc FAIL
log_hera.intel/rt_009_fv3_ccpp_thompson_repro.log:Test 009 fv3_ccpp_thompson FAIL
log_hera.intel/rt_010_fv3_ccpp_thompson_no_aero_repro.log:Test 010 fv3_ccpp_thompson_no_aero FAIL
log_hera.intel/rt_013_fv3_ccpp_gsd_drag_suite_repro.log:Test 013 fv3_ccpp_gsd_drag_suite FAIL
log_hera.intel/rt_014_fv3_ccpp_gsd_sar_repro.log:Test 014 fv3_ccpp_gsd_sar FAIL
log_hera.intel/rt_015_fv3_ccpp_gsd_debug_prod.log:Test 015 fv3_ccpp_gsd_debug FAIL
log_hera.intel/rt_016_fv3_ccpp_gsd_diag3d_debug_prod.log:Test 016 fv3_ccpp_gsd_diag3d_debug FAIL
log_hera.intel/rt_017_fv3_ccpp_gsd_mynnsfc_debug_prod.log:Test 017 fv3_ccpp_gsd_mynnsfc_debug FAIL
log_hera.intel/rt_018_fv3_ccpp_gsd_noah_mynnsfc_debug_prod.log:Test 018 fv3_ccpp_gsd_noah_mynnsfc_debug FAIL
log_hera.intel/rt_019_fv3_ccpp_thompson_no_aero_debug_prod.log:Test 019 fv3_ccpp_thompson_no_aero_debug FAIL
log_hera.intel/rt_020_fv3_ccpp_gsd_sar_25km_debug_prod.log:Test 020 fv3_ccpp_gsd_sar_25km_debug FAIL
```
This is what we expect.

[rt_ccpp_gsd_verify_against_existing_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4618489/rt_ccpp_gsd_verify_against_existing_baseline.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt.conf` against official EMC baseline: all tests pass except `fv3_ccpp_gsd` as expected.

[rt_full_against_emc_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4618826/rt_full_against_emc_baseline.log)

**Comment by climbfuji** [comment]
Last test: create new baseline on hera.intel using rt_ccpp_gsd.conf and verify against it: all tests pass.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4618983/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4618984/rt_ccpp_gsd_verify.log)

**Review by DomHeinzeller — APPROVED** [review]
This PR only updates the submodule pointer.

**Pull request merged**
