### PR TITLE
RUC ice for gsl/develop (replaces #47)

### PR DESCRIPTION
**Pull request by DomHeinzeller**
This PR contains the necessary changes to the regression tests for the RUC ICE implementation in the PRs below.

Associated PRs:

https://github.com/NOAA-GSL/ccpp-physics/pull/65
https://github.com/NOAA-GSL/fv3atm/pull/60
https://github.com/NOAA-GSL/ufs-weather-model/pull/49

For regression testing information, see below.

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel using `rt_ccpp_dev.conf` against baseline created with current head of gsl/develop: The following tests fail as expected (due to the changes in these PRs), but they all run to completion:
```
fv3_ccpp_gsd_drag_suite_unified_ugwp 016 failed in check_result
fv3_ccpp_hrrr 018 failed in check_result
fv3_ccpp_gsd_coldstart 004 failed in check_result
fv3_ccpp_gsd_drag_suite 014 failed in check_result
fv3_ccpp_rap 017 failed in check_result
fv3_ccpp_gsd_debug 022 failed in check_result
fv3_ccpp_gsd_mynnsfc_debug 024 failed in check_result
fv3_ccpp_gsd_diag3d_debug 023 failed in check_result
fv3_ccpp_gsd_mynnsfc 007 failed in check_result
fv3_ccpp_gsd_sar 013 failed in check_result
fv3_ccpp_gsd_unified_ugwp 015 failed in check_result
fv3_ccpp_gsd_sar_debug 027 failed in check_result
fv3_ccpp_gsd 003 failed in check_result
```
[rt_ccpp_dev_original_create.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619022/rt_ccpp_dev_original_create.log)
[rt_ccpp_dev_verify_against_original.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619023/rt_ccpp_dev_verify_against_original.log)
[rt_ccpp_dev_verify_against_original_fail_test.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619025/rt_ccpp_dev_verify_against_original_fail_test.log)

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel using `rt.conf` against official EMC baseline: The following tests fail as expected (due to the changes in these PRs), but they all run to completion:
```
fv3_ccpp_rap 041 failed in check_result
fv3_ccpp_hrrr 042 failed in check_result
fv3_ccpp_gsd 040 failed in check_result
fv3_ccpp_gsd_debug 060 failed in check_result
fv3_ccpp_gsd_diag3d_debug 061 failed in check_result
```
[rt_intel.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619033/rt_intel.log)
[rt_intel_fail_test.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619034/rt_intel_fail_test.log)

**Comment by DomHeinzeller** [comment]
Regression testing on hera.gnu using `rt_gnu.conf` against official EMC baseline: The following test fails as expected (due to the changes in these PRs), but runs to completion:
```
fv3_ccpp_gsd 007 failed in check_result
```
[rt_gnu.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619039/rt_gnu.log)
[rt_gnu_fail_test.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5619040/rt_gnu_fail_test.log)

**Comment by DomHeinzeller** [comment]
Regression testing on cheyenne.intel using `rt_ccpp_dev.conf` (because hera is under maintenance): first create new baseline (to make sure they all work), then verify against it (to test restart reproducibility etc.): all tests pass.

[rt_cheyenne_intel_create.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5624142/rt_cheyenne_intel_create.log)
[rt_cheyenne_intel_verify.log](https://github.com/NOAA-GSL/ufs-weather-model/files/5624143/rt_cheyenne_intel_verify.log)

**Review by tanyasmirnova — APPROVED** [review]

**Review by tanyasmirnova — APPROVED** [review]

**Pull request merged**
