### PR TITLE
 fix bugs found in pbl and ozone 3d diagnostic tendencies

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
PBL tendencies were missing in two schemes; now fixed.

FV3 PR: https://github.com/NOAA-GSD/fv3atm/pull/26

ccpp PR: https://github.com/NOAA-GSD/ccpp-physics/pull/27/

### CODE REVIEW

**Comment by climbfuji** [comment]
All regression tests for GFS_v16beta fail:
```
fv3_ccpp_gfs_v16beta (PROD)
fv3_ccpp_gfs_v16beta (REPRO)
fv3_ccpp_gfs_v16beta_debug
```
I looked inside the run directories, they all crash. Here is the traceback from the debug run:
```
  0:  af create fcst fieldbundle, name=dynrc=           0
  0:  af create fcst fieldbundle, name=phy_nearest_stodrc=           0
  0:  af create fcst fieldbundle, name=phy_bilinearrc=           0
  0:  in fcst,init total time:    21.8321559429169
 20: forrtl: severe (174): SIGSEGV, segmentation fault occurred
 20: Image              PC                Routine            Line        Source
 20: fv3.exe            0000000006E26E7C  Unknown               Unknown  Unknown
 20: libpthread-2.17.s  00002B7D7C95B5F0  Unknown               Unknown  Unknown
 20: fv3.exe            0000000003647000  satmedmfvdifq_mp_        1327  satmedmfvdifq.F
 20: fv3.exe            0000000002F0D6EB  ccpp_fv3_gfs_v16b         985  ccpp_FV3_GFS_v16beta_physics_cap.F90
 20: fv3.exe            0000000002D5A35D  ccpp_static_api_m         229  ccpp_static_api.F90
 20: fv3.exe            0000000002D62D55  ccpp_driver_mp_cc         234  CCPP_driver.F90
 20: libiomp5.so        00002B7D7CF55A43  __kmp_invoke_micr     Unknown  Unknown
 20: libiomp5.so        00002B7D7CF192C6  __kmp_fork_call       Unknown  Unknown
 20: libiomp5.so        00002B7D7CED8BB0  __kmpc_fork_call      Unknown  Unknown
 20: fv3.exe            0000000002D6040A  ccpp_driver_mp_cc         214  CCPP_driver.F90
 20: fv3.exe            000000000065BA91  atmos_model_mod_m         392  atmos_model.F90
 20: fv3.exe            000000000063889E  module_fcst_grid_         739  module_fcst_grid_comp.F90
...
```

**Comment by DomHeinzeller** [comment]
ufs-weather-model was just updated (PR https://github.com/NOAA-GSD/ufs-weather-model/pull/21; submodule pointer update only). Please update your branch. Thanks!

**Comment by SamuelTrahanNOAA** [comment]
> ufs-weather-model was just updated (PR #21; submodule pointer update only). Please update your branch. Thanks!

Your request confuses me. The PR #21 updates the FV3, and I am also updating the FV3. This PR will, out of necessity, point to a different hash of the FV3.

Nonetheless, the underlying changes are merged.

**Comment by DomHeinzeller** [comment]
> > ufs-weather-model was just updated (PR #21; submodule pointer update only). Please update your branch. Thanks!
> 
> Your request confuses me. The PR #21 updates the FV3, and I am also updating the FV3. This PR will, out of necessity, point to a different hash of the FV3.
> 
> Nonetheless, the underlying changes are merged.

Sorry if this wasn't clear. The ufs-weather-model repository was also updated in PR #21. You didn't pull in this change (which again was just a submodule pointer update), and therefore GitHub is telling me that there is a merge conflict (FV3).

Once the merge conflict is resolved, I will approve this PR. All tests finished as expected, see following comments here.

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel:

(1) using `rt.conf` against official EMC baseline: all tests pass except `fv3_ccpp_gsd` as expected

[rt_full.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4625673/rt_full.log)
[rt_full_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4625674/rt_full_fail_test.log)

(2) using `rt_ccpp_gsd`.conf against a temporary baseline created with the current head of gsd/develop: all tests pass

[rt_ccpp_gsd.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4625677/rt_ccpp_gsd.log)

**Comment by DomHeinzeller** [comment]
I merged fv3atm, can you please update the submodule pointer to:
```
commit bfe13b020d34e1d7a9dcfd416703281bebf542cb (HEAD, origin/gsd/develop, origin/HEAD)
Author: Samuel Trahan (NOAA contractor) <39415369+SamuelTrahanNOAA@users.noreply.github.com>
Date:   Thu May 14 09:04:06 2020 -0400

     fix bugs found in pbl and ozone 3d diagnostic tendencies (#26)

    PBL tendencies were missing in two schemes; now fixed. Squashed commit of the following:

    * fix bugs found in pbl and ozone 3d diagnostic tendencies
    * remove debugging prints
    * implied shape arrays for five variables
    * more block labels in CCPP
    * make the logging less wordy
    * point to hash 238c84cb3c789056c701b70d3373e640ed4fa599 of ccpp/physics
```
Thanks!

**Comment by SamuelTrahanNOAA** [comment]
> update the submodule pointer to

Done.

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
