### PR TITLE
GF_Tune_Oct2021

### PR DESCRIPTION
**Pull request by hannahcbarnes**
- Aerosol-awareness in GF is turned back on
- clwdet (cloud-water detrainment) is tuned
- evfact (evaporation fraction) and tun_rad_deep, tun_rad_mid (radiation factors) are made scale-aware

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
Associated PRs:

https://github.com/NOAA-GSL/ccpp-physics/pull/108
https://github.com/NOAA-GSL/fv3atm/pull/110
https://github.com/NOAA-GSL/ufs-weather-model/pull/104

**Comment by DomHeinzeller** [comment]
Regression testing on Hera with Intel and GNU:

1. Using `rt_ccpp_dev.conf`, create new temporary baselines and verify against them. All tests pass, except `fv3_gsd_sar` and `fv3_gsd_sar_debug`. This is a known issue and requires an update to the FV3 dycore, which will be committed to the authoritative repositories today/tomorrow and then brought over to gsl/develop.

[rt_ccpp_dev_hera_gnu_create.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382596/rt_ccpp_dev_hera_gnu_create.log)
[rt_ccpp_dev_hera_gnu_verify.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382598/rt_ccpp_dev_hera_gnu_verify.log)
[rt_ccpp_dev_hera_intel_create.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382599/rt_ccpp_dev_hera_intel_create.log)
[rt_ccpp_dev_hera_intel_verify.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382600/rt_ccpp_dev_hera_intel_verify.log)

2. Testing against existing/official baselines using `rt.conf`/`rt_gnu.conf`: all tests pass, except those that are expected to fail due to b4b mismatches (because of changes in gsl/develop that are not yet in the authoritative repositories). All of these tests run to completion.

[rt_hera_gnu_verify_against_existing.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382585/rt_hera_gnu_verify_against_existing.log)
[rt_rt_hera_gnu_verify_against_existing_fail_test.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382586/rt_rt_hera_gnu_verify_against_existing_fail_test.log)
[rt_hera_intel_verify_against_existing.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382587/rt_hera_intel_verify_against_existing.log)
[rt_hera_intel_verify_against_existing_fail_test.log](https://github.com/NOAA-GSL/ufs-weather-model/files/7382588/rt_hera_intel_verify_against_existing_fail_test.log)

These PRs are ready to merge.

**Comment by DomHeinzeller** [comment]
@hannahcbarnes Your next chance to try this! Please update the fv3atm submodule pointer in your ufs-weather-model branch, the correct hash is bf540b0. Thanks.

**Comment by hannahcbarnes** [comment]
Ok I saw the correct hash this time. Hopefully it worked

**Comment by DomHeinzeller** [comment]
This time you added several changes that shouldn't be there, the only change should be the fv3atm submodule pointer. See https://github.com/NOAA-GSL/ufs-weather-model/pull/104/files. Please revert all changes except the submodule pointer update.

**Review by DomHeinzeller — APPROVED** [review]

**Comment by hannahcbarnes** [comment]
Thanks Dom. Glad that worked this time.

**Pull request merged**
