### PR TITLE
Cleanup of Thompson MP cloud effective radii calculation

### PR DESCRIPTION
**Pull request by climbfuji**
Changes in this PR:
- set namelist parameter effr_in to .true. in the GSD namelist templates

Associated PRs:
https://github.com/NOAA-GSD/ccpp-physics/pull/30
https://github.com/NOAA-GSD/fv3atm/pull/31
https://github.com/NOAA-GSD/ufs-weather-model/pull/24

For regression testing information, see below **NOT YET**.

### CODE REVIEW

**Comment by climbfuji** [comment]
@tanyasmirnova @hannahcbarnes @joeolson42 please see this PR and associated PRs for the changes we discussed yesterday. By not passing the optional arguments for the cloud effective radii to `mp_thompson_init` and `mp_thompson_run` (see https://github.com/NOAA-GSD/fv3atm/pull/31, `ccpp_prebuild_config.py`), the calculation of the radii is turned off in both and now only happens in `GFS_rrtmg_pre_run`.

**Comment by climbfuji** [comment]
Manual testing on macOS with GNU: running the original code (head of gsd/develop, with `effr_in = .false.`) of the `fv3_ccpp_gsd` suite against the code in this PR (with `effr_in = .true.`) for the C96 regression test. After two hours of integration, I see a warming signal over the poles. Displayed here is tile 6, left is original, right is new, center is new minus original.

Screen Shot 2020-06-02 at 7 15 18 AM

Update after adding the number concentration calculation bugfix in GFS_suite_interstitial_4_run (https://github.com/NOAA-GSD/ccpp-physics/pull/30/commits/2aa91ae97ef29195995317ee2285972c0abc1afb): same signal, probably slightly more pronounced (showing only diff new minus original, i.e. center plot above)

Screen Shot 2020-06-02 at 4 29 46 PM

**Comment by climbfuji** [comment]
Testing on hera.intel: reran manual test of current head of gsd/develop (with default value effr_in = .false.) against the new code (with default value effr_in = .true.) for the usual testcase "test_c768_20191120_gsdnoah". The 24h difference plots of 2m temperature (new minus original code) show a warming over the poles in particular, but also in other areas. This plot is for the entire globe (coastlines can't be seen, because they are white).

This is consistent with our expectation.

Screen Shot 2020-06-02 at 8 32 37 PM

I also compared the head of gsd/develop with `effr_in = .true.` against the new code for the same test case. The results are encouraging, since they show a consistent warming signal across the globe,

Screen Shot 2020-06-02 at 9 46 46 PM

**Comment by climbfuji** [comment]
Regression testing on hera.intel against EMC baseline (using `rt.conf`): tests passed and expected as failed (because GSD physics have changed compared to the EMC baseline):
```
bash-4.2$ grep -e PASS log_hera.intel/*
log_hera.intel/rt_001_fv3_ccpp_control_prod.log:Test 001 fv3_ccpp_control PASS
log_hera.intel/rt_002_fv3_ccpp_decomp_prod.log:Test 002 fv3_ccpp_decomp PASS
log_hera.intel/rt_003_fv3_ccpp_2threads_prod.log:Test 003 fv3_ccpp_2threads PASS
log_hera.intel/rt_004_fv3_ccpp_restart_prod.log:Test 004 fv3_ccpp_restart PASS
log_hera.intel/rt_005_fv3_ccpp_read_inc_prod.log:Test 005 fv3_ccpp_read_inc PASS
log_hera.intel/rt_006_fv3_ccpp_wrtGauss_netcdf_esmf_prod.log:Test 006 fv3_ccpp_wrtGauss_netcdf_esmf PASS
log_hera.intel/rt_007_fv3_ccpp_wrtGauss_netcdf_prod.log:Test 007 fv3_ccpp_wrtGauss_netcdf PASS
log_hera.intel/rt_008_fv3_ccpp_wrtGlatlon_netcdf_prod.log:Test 008 fv3_ccpp_wrtGlatlon_netcdf PASS
log_hera.intel/rt_009_fv3_ccpp_wrtGauss_nemsio_prod.log:Test 009 fv3_ccpp_wrtGauss_nemsio PASS
log_hera.intel/rt_010_fv3_ccpp_wrtGauss_nemsio_c192_prod.log:Test 010 fv3_ccpp_wrtGauss_nemsio_c192 PASS
log_hera.intel/rt_011_fv3_ccpp_stochy_prod.log:Test 011 fv3_ccpp_stochy PASS
log_hera.intel/rt_012_fv3_ccpp_iau_prod.log:Test 012 fv3_ccpp_iau PASS
log_hera.intel/rt_013_fv3_ccpp_ca_prod.log:Test 013 fv3_ccpp_ca PASS
log_hera.intel/rt_014_fv3_ccpp_lheatstrg_prod.log:Test 014 fv3_ccpp_lheatstrg PASS
log_hera.intel/rt_015_fv3_ccpp_gfdlmprad_prod.log:Test 015 fv3_ccpp_gfdlmprad PASS
log_hera.intel/rt_016_fv3_ccpp_gfdlmprad_atmwav_prod.log:Test 016 fv3_ccpp_gfdlmprad_atmwav PASS
log_hera.intel/rt_017_fv3_ccpp_wrtGauss_nemsio_c768_prod.log:Test 017 fv3_ccpp_wrtGauss_nemsio_c768 PASS
log_hera.intel/rt_018_fv3_ccpp_control_32bit_prod.log:Test 018 fv3_ccpp_control_32bit PASS
log_hera.intel/rt_019_fv3_ccpp_stretched_prod.log:Test 019 fv3_ccpp_stretched PASS
log_hera.intel/rt_020_fv3_ccpp_stretched_nest_prod.log:Test 020 fv3_ccpp_stretched_nest PASS
log_hera.intel/rt_021_fv3_ccpp_regional_control_prod.log:Test 021 fv3_ccpp_regional_control PASS
log_hera.intel/rt_022_fv3_ccpp_regional_restart_prod.log:Test 022 fv3_ccpp_regional_restart PASS
log_hera.intel/rt_023_fv3_ccpp_regional_quilt_prod.log:Test 023 fv3_ccpp_regional_quilt PASS
log_hera.intel/rt_024_fv3_ccpp_regional_c768_prod.log:Test 024 fv3_ccpp_regional_c768 PASS
log_hera.intel/rt_025_fv3_ccpp_control_debug_prod.log:Test 025 fv3_ccpp_control_debug PASS
log_hera.intel/rt_026_fv3_ccpp_stretched_nest_debug_prod.log:Test 026 fv3_ccpp_stretched_nest_debug PASS
log_hera.intel/rt_027_fv3_ccpp_gfdlmp_prod.log:Test 027 fv3_ccpp_gfdlmp PASS
log_hera.intel/rt_028_fv3_ccpp_gfdlmprad_gwd_prod.log:Test 028 fv3_ccpp_gfdlmprad_gwd PASS
log_hera.intel/rt_029_fv3_ccpp_gfdlmprad_noahmp_prod.log:Test 029 fv3_ccpp_gfdlmprad_noahmp PASS
log_hera.intel/rt_030_fv3_ccpp_csawmg_prod.log:Test 030 fv3_ccpp_csawmg PASS
log_hera.intel/rt_031_fv3_ccpp_satmedmf_prod.log:Test 031 fv3_ccpp_satmedmf PASS
log_hera.intel/rt_032_fv3_ccpp_satmedmfq_prod.log:Test 032 fv3_ccpp_satmedmfq PASS
log_hera.intel/rt_033_fv3_ccpp_gfdlmp_32bit_prod.log:Test 033 fv3_ccpp_gfdlmp_32bit PASS
log_hera.intel/rt_034_fv3_ccpp_gfdlmprad_32bit_post_prod.log:Test 034 fv3_ccpp_gfdlmprad_32bit_post PASS
log_hera.intel/rt_035_fv3_ccpp_cpt_prod.log:Test 035 fv3_ccpp_cpt PASS
log_hera.intel/rt_039_fv3_ccpp_gfs_v15p2_prod.log:Test 039 fv3_ccpp_gfs_v15p2 PASS
log_hera.intel/rt_040_fv3_ccpp_gfs_v16beta_prod.log:Test 040 fv3_ccpp_gfs_v16beta PASS
log_hera.intel/rt_041_fv3_ccpp_rrtmgp_prod.log:Test 041 fv3_ccpp_rrtmgp PASS
log_hera.intel/rt_042_fv3_ccpp_gfs_v15p2_debug_prod.log:Test 042 fv3_ccpp_gfs_v15p2_debug PASS
log_hera.intel/rt_043_fv3_ccpp_gfs_v16beta_debug_prod.log:Test 043 fv3_ccpp_gfs_v16beta_debug PASS
log_hera.intel/rt_044_fv3_ccpp_rrtmgp_debug_prod.log:Test 044 fv3_ccpp_rrtmgp_debug PASS
log_hera.intel/rt_048_fv3_ccpp_gfsv16_csawmg_prod.log:Test 048 fv3_ccpp_gfsv16_csawmg PASS
log_hera.intel/rt_049_fv3_ccpp_gfsv16_csawmgt_prod.log:Test 049 fv3_ccpp_gfsv16_csawmgt PASS
log_hera.intel/rt_050_fv3_ccpp_gocart_clm_prod.log:Test 050 fv3_ccpp_gocart_clm PASS
bash-4.2$ grep -e FAIL log_hera.intel/*
log_hera.intel/rt_036_fv3_ccpp_gsd_prod.log:Test 036 fv3_ccpp_gsd FAIL
log_hera.intel/rt_037_fv3_ccpp_thompson_prod.log:Test 037 fv3_ccpp_thompson FAIL
log_hera.intel/rt_038_fv3_ccpp_thompson_no_aero_prod.log:Test 038 fv3_ccpp_thompson_no_aero FAIL
log_hera.intel/rt_045_fv3_ccpp_gsd_debug_prod.log:Test 045 fv3_ccpp_gsd_debug FAIL
log_hera.intel/rt_046_fv3_ccpp_thompson_debug_prod.log:Test 046 fv3_ccpp_thompson_debug FAIL
log_hera.intel/rt_047_fv3_ccpp_thompson_no_aero_debug_prod.log:Test 047 fv3_ccpp_thompson_no_aero_debug FAIL
```
All of them ran to completion.

[rt_full_against_emc_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4720892/rt_full_against_emc_baseline.log)
[rt_full_against_emc_baseline_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4720894/rt_full_against_emc_baseline_fail_test.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel against existing GSD baseline (using `rt_ccpp_gsd.conf`; created with head of gsd/develop): all tests run to completion, but all results are different.

For tests not using Thompson MP (`fv3_ccpp_gf`, `fv3_ccpp_mynn`), the only difference is in the purely diagnostic cloud effective radii in the restart files (`RESTART/phy_data.tile?.nc`), everything else is b4b identical. This is expected, because the cloud effective radii from GFDL-MP are not hooked up with the subgrid-scale clouds and the radiation for MYNN and GF.

All other tests using Thompson MP have different results, as expected.

[rt_ccpp_gsd_create_original_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4723694/rt_ccpp_gsd_create_original_baseline.log)
[rt_ccpp_gsd_verify_against_original_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4723695/rt_ccpp_gsd_verify_against_original_baseline.log)
[rt_ccpp_gsd_verify_against_original_baseline_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4723696/rt_ccpp_gsd_verify_against_original_baseline_fail_test.log)

**Comment by climbfuji** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf`: first create new baseline, then verify against it: all tests pass.

[rt_ccpp_gsd_create_new_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4724408/rt_ccpp_gsd_create_new_baseline.log)
[rt_ccpp_gsd_verify_against_new_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4724410/rt_ccpp_gsd_verify_against_new_baseline.log)

**Comment by climbfuji** [comment]
@haiqinli @hannahcbarnes @tanyasmirnova @joeolson42 these PRs are ready to merge. Please let me know if you approve these changes or not. Thanks!

**Comment by hannahcbarnes** [comment]
@climbfuji The change to GFS_suite_interstitial looks good to me. Thanks for adding it. I tried to look at the effective radii reorganization but it may be better to have @tanyasmirnova @joeolson42 take a look since they are more familiar with that portion of the code.

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
