### PR TITLE
Move plumerise to gocart repo

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR and associated PRs move the GSD CHEM plum rise modules from ccpp-physics to the GOCART repository. In ufs-weather-model, a `gocart-interface` is defined in the top-level `CMakeLists.txt`. Also, since target `GOCART` must now be enabled when `FV3` is used, the application `ATMC` is removed. Target `GOCART` is now built as part of the application `ATM`.

## Testing

Testing:

- ran the regression tests on hera against the existing EMC baselines for Intel (`rt.conf`) and GNU (`rt_gnu.conf`), all tests passed.
[rt_hera_intel_verify_against_existing.log](https://github.com/NOAA-GSL/ufs-weather-model/files/6361503/rt_hera_intel_verify_against_existing.log)
[rt_hera_gnu_verify_against_existing.log](https://github.com/NOAA-GSL/ufs-weather-model/files/6361504/rt_hera_gnu_verify_against_existing.log)

- created new baselines using `rt_ccpp_dev.conf` on Hera for both Intel and GNU and verified against it, all tests pass.
[rt_ccpp_dev_hera_gnu_create.log](https://github.com/NOAA-GSL/ufs-weather-model/files/6361507/rt_ccpp_dev_hera_gnu_create.log)
[rt_ccpp_dev_hera_gnu_verify.log](https://github.com/NOAA-GSL/ufs-weather-model/files/6361508/rt_ccpp_dev_hera_gnu_verify.log)
[rt_ccpp_dev_hera_intel_create.log](https://github.com/NOAA-GSL/ufs-weather-model/files/6361517/rt_ccpp_dev_hera_intel_create.log)
[rt_ccpp_dev_hera_intel_verify.log](https://github.com/NOAA-GSL/ufs-weather-model/files/6361518/rt_ccpp_dev_hera_intel_verify.log)

- verification against previous code: there are roundoff differences of the order of `1e-20` after 24h of integration at a handful of grid points for the chemical species `so2`, `sulf`, `pp25`, `bc1`, `bc2`, `oc1`, `oc2`. These variables are in both the `dynf???.nemsio` and `RESTART/fv_tracer.res.tile?.nc` files. All other variables in those files, and all other files  are b4b identical after 24h.
 ```
baseline dir = /scratch1/NCEPDEV/stmp4/Dom.Heinzeller/FV3_RT/REGRESSION_TEST_INTEL/fv3_gfdlmp_gsd_chem_repro
working dir  = /scratch1/NCEPDEV/stmp2/Dom.Heinzeller/FV3_RT/rt_101361/fv3_gfdlmp_gsd_chem_repro
Checking test 021 fv3_gfdlmp_gsd_chem results ....
 Comparing atmos_4xdaily.tile1.nc .........OK
 Comparing atmos_4xdaily.tile2.nc .........OK
 Comparing atmos_4xdaily.tile3.nc .........OK
 Comparing atmos_4xdaily.tile4.nc .........OK
 Comparing atmos_4xdaily.tile5.nc .........OK
 Comparing atmos_4xdaily.tile6.nc .........OK
 Comparing phyf000.nemsio .........OK
 Comparing phyf024.nemsio .........OK
 Comparing dynf000.nemsio .........OK
 Comparing dynf024.nemsio .........NOT OK
 Comparing RESTART/coupler.res .........OK
 Comparing RESTART/fv_core.res.nc .........OK
 Comparing RESTART/fv_core.res.tile1.nc .........OK
 Comparing RESTART/fv_core.res.tile2.nc .........OK
 Comparing RESTART/fv_core.res.tile3.nc .........OK
 Comparing RESTART/fv_core.res.tile4.nc .........OK
 Comparing RESTART/fv_core.res.tile5.nc .........OK
 Comparing RESTART/fv_core.res.tile6.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile1.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile2.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile3.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile4.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile5.nc .........OK
 Comparing RESTART/fv_srf_wnd.res.tile6.nc .........OK
 Comparing RESTART/fv_tracer.res.tile1.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile2.nc ............ALT CHECK......OK
 Comparing RESTART/fv_tracer.res.tile3.nc ............ALT CHECK......OK
 Comparing RESTART/fv_tracer.res.tile4.nc ............ALT CHECK......OK
 Comparing RESTART/fv_tracer.res.tile5.nc ............ALT CHECK......NOT OK
 Comparing RESTART/fv_tracer.res.tile6.nc ............ALT CHECK......OK
 Comparing RESTART/sfc_data.tile1.nc .........OK
 Comparing RESTART/sfc_data.tile2.nc .........OK
 Comparing RESTART/sfc_data.tile3.nc .........OK
 Comparing RESTART/sfc_data.tile4.nc .........OK
 Comparing RESTART/sfc_data.tile5.nc .........OK
 Comparing RESTART/sfc_data.tile6.nc .........OK
 Comparing RESTART/phy_data.tile1.nc .........OK
 Comparing RESTART/phy_data.tile2.nc .........OK
 Comparing RESTART/phy_data.tile3.nc .........OK
 Comparing RESTART/phy_data.tile4.nc .........OK
 Comparing RESTART/phy_data.tile5.nc .........OK
 Comparing RESTART/phy_data.tile6.nc .........OK
 ```

## Dependencies

https://github.com/NOAA-GSL/ccpp-physics/pull/87
https://github.com/NOAA-GSL/fv3atm/pull/84
https://github.com/NOAA-GSL/GOCART/pull/2
https://github.com/NOAA-GSL/ufs-weather-model/pull/73

### CODE REVIEW

**Review by haiqinli — APPROVED** [review]

**Review by SamuelTrahanNOAA — CHANGES_REQUESTED** [review]
If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.

**Review by SamuelTrahanNOAA — CHANGES_REQUESTED** [review]
If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.

**Comment by climbfuji** [comment]
> If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.

The goal is to remove the plum-rise modules from ccpp-physics and use a single source that can be shared with NASA and used as NUOPC component. It was discussed in several meetings that the code needs to go to GOCART.

The CCPP entry points could move, but don't have to, and there are reasons for not moving them (they "belong" to CCPP and not into a "random" directory). We have examples in CCPP where the wrappers are in ccpp-physics and the core routines come from other repositories (e.g. RRTMGP), albeit in this case rrtmgp is a submodule. If RRTMGP becomes a component that will be coupled either directly via CCPP or indirectly as NUOPC component, we will have the same situation. You should think of GOCART (or RRTMGP) as external modules/libraries that provide access to core routines that are shared with other models (e.g. ICON for RRTMGP)/modeling components (e.g. NUOPC) and for which "we" maintain the CCPP entry points. We don't require the NCEPLIBS, netCDF, ... to sit in the same repository as the ccpp-entry points either, yet we use them.

**Comment by SamuelTrahanNOAA** [comment]
> > If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.
> 
> The goal is to remove the plum-rise modules from ccpp-physics and use a single source that can be shared with NASA and used as NUOPC component. It was discussed in several meetings that the code needs to go to GOCART.
> 
> The CCPP entry points could move, but don't have to, and there are reasons for not moving them (they "belong" to CCPP and not into a "random" directory). We have examples in CCPP where the wrappers are in ccpp-physics and the core routines come from other repositories (e.g. RRTMGP), albeit in this case rrtmgp is a submodule. If RRTMGP becomes a component that will be coupled either directly via CCPP or indirectly as NUOPC component, we will have the same situation. You should think of GOCART (or RRTMGP) as external modules/libraries that provide access to core routines that are shared with other models (e.g. ICON for RRTMGP)/modeling components (e.g. NUOPC) and for which "we" maintain the CCPP entry points. We don't require the NCEPLIBS, netCDF, ... to sit in the same repository as the ccpp-entry points either, yet we use them.

My suggested solution is to move everything except wrappers into GOCART.

**Comment by DomHeinzeller** [comment]
> > > If a new plumerise module is needed, it should be copied into gsd-chem, or all of gsd-chem's non-wrapper modules should be in GOCART. This half-way solution makes the code worse, not better. As an interim solution, the modules should be copied into gsd-chem, and we should make an end goal of either keeping everything there, or moving it to GOCART.
> > 
> > 
> > The goal is to remove the plum-rise modules from ccpp-physics and use a single source that can be shared with NASA and used as NUOPC component. It was discussed in several meetings that the code needs to go to GOCART.
> > The CCPP entry points could move, but don't have to, and there are reasons for not moving them (they "belong" to CCPP and not into a "random" directory). We have examples in CCPP where the wrappers are in ccpp-physics and the core routines come from other repositories (e.g. RRTMGP), albeit in this case rrtmgp is a submodule. If RRTMGP becomes a component that will be coupled either directly via CCPP or indirectly as NUOPC component, we will have the same situation. You should think of GOCART (or RRTMGP) as external modules/libraries that provide access to core routines that are shared with other models (e.g. ICON for RRTMGP)/modeling components (e.g. NUOPC) and for which "we" maintain the CCPP entry points. We don't require the NCEPLIBS, netCDF, ... to sit in the same repository as the ccpp-entry points either, yet we use them.
> 
> My suggested solution is to move everything except wrappers into GOCART.

I am fine with that, but can we do this in a next step so that this PR can be merged without rerunning the tests? The purpose of this PR was to add a demonstrator for the capability to call the plum rise module from GOCART. I will also need a list of all files that should be moved from someone.

**Comment by DomHeinzeller** [comment]
Ok, the accidental merge of fv3atm means I'll get everything merged bottom-to-top and fv3atm fixed, then move the remaining files with @zhanglikate's / @haiqinli's help.

**Comment by SamuelTrahanNOAA** [comment]
> I am fine with that, but can we do this in a next step so that this PR can be merged without rerunning the tests? The purpose of this PR was to add a demonstrator for the capability to call the plum rise module from GOCART. I will also need a list of all files that should be moved from someone.

At the very least, the config modules should not be duplicated. Those modules have bugs (hard-coded to GOCART_SIMPLE) which will be harder to fix if they are duplicated. The original developer should have done this properly in the first place.

**Comment by DomHeinzeller** [comment]
> > I am fine with that, but can we do this in a next step so that this PR can be merged without rerunning the tests? The purpose of this PR was to add a demonstrator for the capability to call the plum rise module from GOCART. I will also need a list of all files that should be moved from someone.
> 
> At the very least, the config modules should not be duplicated. Those modules have bugs (hard-coded to GOCART_SIMPLE) which will be harder to fix if they are duplicated. The original developer should have done this properly in the first place.

Yes, absolutely agree. I will make this change with the next PR.

**Comment by DomHeinzeller** [comment]
@SamuelTrahanNOAA @zhanglikate the b4b differences that I described in the first comment box in this PR are ok in my opinion. `1e-20` diff after 24h for selected chemical species with no impact on the dynamics or other physics, looks like pure round-off differences.

I will get started with what Sam requested, moving all gsd-chem process modules and remove the duplicate config files, within the next few hours.

**Pull request merged**
