### PR TITLE
Update gsd/develop from develop 2020/06/16

### PR DESCRIPTION
**Pull request by climbfuji**
Update gsd/develop from develop as of 2020/06/16. The changes include:
- build config updates for several machines
- use ecflow to submit compile jobs instead of running on login nodes
- GFS v16 updates
- merge GFS and HWRF saSAS deep/shallow convection
- update FV3 dycore
- known issue: with these changes, the regression test `fv3_ccpp_gsd_sar_25km_debug` gives different results from run to run (or crashes with floating invalid errors in the dycore) for the following variables in `dynf*.nc`: maxvort01, maxvort02, uhmin03, uhmin25. Everything else is b4b identical (including the checksums at the end of the model run), i.e. these are purely diagnostic variables produced by the dycore; temporarily turned off this test in `rt_ccpp_gsd.conf`

Associated PRs:
https://github.com/NOAA-GSD/ufs-weather-model/pull/29
https://github.com/NOAA-GSD/fv3atm/pull/37
https://github.com/NOAA-GSD/ccpp-physics/pull/37
https://github.com/NOAA-GSD/ccpp-framework/pull/5
https://github.com/NOAA-GSD/GFDL_atmos_cubed_sphere/pull/3

For regression testing, see below **NOT YET**.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing on hera.intel against official EMC baseline using `rt.conf`: all tests pass, except the usual suspects (but all of them complete):
```
fv3_ccpp_gsd_debug
fv3_ccpp_thompson
fv3_ccpp_thompson_no_aero
fv3_ccpp_thompson_no_aero_debug
fv3_ccpp_thompson_debug
fv3_ccpp_gsd
```
[rt_full.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4795166/rt_full.log)
[rt_full_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4795167/rt_full_fail_test.log)

**Comment by climbfuji** [comment]
@tanyasmirnova @hannahcbarnes @joeolson42 @haiqinli FYI see this set of PRs for the update of gsd/develop from the authoritative branches, including the GFSv16 updates for `sfc_diff.f`.

**Comment by hannahcbarnes** [comment]
I glanced at the changes. In terms of the physics changes it seems to be a lot of renaming. Though, I did see where sfc_diff.f was rolled back. These changes are ok with me, but others may be a better judge of them changes.

**Comment by climbfuji** [comment]
Regression testing on hera.intel using rt_ccpp_gsd.conf: first create new baseline, then verify against it: all tests pass.

[rt_ccpp_gsd_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4802090/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/4802091/rt_ccpp_gsd_verify.log)

**Review by DomHeinzeller — APPROVED** [review]

**Pull request merged**
