### PR TITLE
Move RUC LSM soil variables initialization to lsm_ruc_init

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Update `.gitmodules` and submodule pointers for fv3atm for code review and testing for the PRs listed below.

## Testing

For regression testing information, see below.

## Dependencies

https://github.com/NOAA-GSD/ccpp-framework/pull/9
https://github.com/NOAA-GSD/ccpp-physics/pull/51
https://github.com/NOAA-GSD/ccpp-physics/pull/56
https://github.com/NOAA-GSD/fv3atm/pull/51
https://github.com/NOAA-GSD/ufs-weather-model/pull/42

### CODE REVIEW

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel against official EMC baseline using `rt.conf`. The following tests fail as expected with b4b differences (because of previous to the GSL physics and new changes to RUC LSM), but all tests run to completion.
```
fv3_ccpp_thompson 042 failed in check_result
fv3_ccpp_thompson_no_aero 043 failed in check_result
fv3_ccpp_hrrr 041 failed in check_result
fv3_ccpp_rap 040 failed in check_result
fv3_ccpp_rrfs_v1beta 044 failed in check_result
fv3_ccpp_gsd 039 failed in check_result
fv3_ccpp_rrfs_v1beta_debug 057 failed in check_result
fv3_ccpp_gsd_debug 053 failed in check_result
fv3_ccpp_gsd_diag3d_debug 054 failed in check_result
fv3_ccpp_thompson_no_aero_debug 056 failed in check_result
fv3_ccpp_thompson_debug 055 failed in check_result
```
[rt_hera_intel.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5380831/rt_hera_intel.log)
[rt_hera_intel_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5380832/rt_hera_intel_fail_test.log)

**Comment by DomHeinzeller** [comment]
Regression testing on hera.gnu against official EMC baseline using `rt_gnu.conf`. The following tests fail as expected with b4b differences (because of previous to the GSL physics and new changes to RUC LSM), but all tests run to completion.
```
fv3_ccpp_thompson 006 failed in check_result
fv3_ccpp_thompson_no_aero 007 failed in check_result
fv3_ccpp_rrfs_v1beta 008 failed in check_result
fv3_ccpp_gsd 005 failed in check_result
```
[rt_hera_gnu.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5385753/rt_hera_gnu.log)
[rt_hera_gnu_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5385754/rt_hera_gnu_fail_test.log)

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel against a baseline created with current head of gsd/develop using `rt_ccpp_gsd.conf`. All tests that use RUC LSM fail with b4b differences (as expected due to the changes in this PR), but run to completion. All other tests not involving RUC LSM give b4b identical results with the current head of gsd/develop.

Failed tests:
```
fv3_ccpp_gsd_coldstart 004 failed in check_result
fv3_ccpp_gsd_sar_25km_debug 022 failed in check_result
fv3_ccpp_gsd 003 failed in check_result
fv3_ccpp_gsd_debug 017 failed in check_result
fv3_ccpp_gsd_mynnsfc_debug 019 failed in check_result
fv3_ccpp_gsd_diag3d_debug 018 failed in check_result
fv3_ccpp_rap 015 failed in check_result
fv3_ccpp_gsd_drag_suite 014 failed in check_result
fv3_ccpp_gsd_mynnsfc 007 failed in check_result
fv3_ccpp_hrrr 016 failed in check_result
fv3_ccpp_gsd_sar 013 failed in check_result
```
[rt_hera_intel_ccpp_gsd_verify_against_existing_gsd_baseline.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5380840/rt_hera_intel_ccpp_gsd_verify_against_existing_gsd_baseline.log)
[rt_hera_intel_ccpp_gsd_verify_against_existing_gsd_baseline_fail_test.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5380841/rt_hera_intel_ccpp_gsd_verify_against_existing_gsd_baseline_fail_test.log)

**Comment by DomHeinzeller** [comment]
@tanyasmirnova - not so good news, I get run-to-run differences for everything that involves RUC LSM.

I created a new baseline using
```
./rt.sh -l rt_ccpp_gsd.conf -c -e 2>&1 | tee rt_ccpp_gsd_hera_intel_create.log
```
and then verified against it using
```
./rt.sh -l rt_ccpp_gsd.conf -m -e 2>&1 | tee rt_ccpp_gsd_hera_intel_verify.log
```
and these tests fail:
```
fv3_ccpp_gsd_coldstart 004 failed in check_result
fv3_ccpp_hrrr 016 failed in check_result
fv3_ccpp_gsd_drag_suite 014 failed in check_result
fv3_ccpp_rap 015 failed in check_result
fv3_ccpp_gsd 003 failed in check_result
fv3_ccpp_gsd_mynnsfc 007 failed in check_result
```
This looks a lot like uninitialized variables ...

**Comment by DomHeinzeller** [comment]
A bit more information. For test `fv3_ccpp_gsd_coldstart_repro`, I see differences in `soill5`-`soill9` in the `phyf???.tile?.nc` output files - but no differences in the `dynf???.tile?.nc` files. For `fv3_ccpp_hrrr_repro`, I see differences in `phyf???.tile?.nc`  and `RESTART/sfc_data.tile?.nc`, but not in the `dynf*.nc` or `RESTART/fv_tracer*.nc` or `RESTART/phy_data.tile?.nc` files. Seems like the diagnostic output from the additional RUC subsurface levels 5-9 is the problem.

**Comment by tanyasmirnova** [comment]
Thank you, Dom.
The problem must be over water where soil variables in the top 4 layers are set to the Noah 4-layer arrays.
Looking into it. I also tried to accomodate frac_grid=.true. - could be something is not right there.

**Comment by tanyasmirnova** [comment]
Dom, I have committed several changes to my PR that remove fractional land cover from the initialization. Now I think it should not be there, because the goal of initialization is just to get 9-level soil fields from the 4-layer data. Does it make sense?

**Comment by DomHeinzeller** [comment]
> Dom, I have committed several changes to my PR that remove fractional land cover from the initialization. Now I think it should not be there, because the goal of initialization is just to get 9-level soil fields from the 4-layer data. Does it make sense?

Thanks, @tanyasmirnova - I'll test this version.

**Comment by DomHeinzeller** [comment]
> > Dom, I have committed several changes to my PR that remove fractional land cover from the initialization. Now I think it should not be there, because the goal of initialization is just to get 9-level soil fields from the 4-layer data. Does it make sense?
> 
> Thanks, @tanyasmirnova - I'll test this version.

Ok, this is better. Now I only get one failure, and that is for the restart (warmstart) run. I think I can figure this out if you don't have time to do so.

**Comment by tanyasmirnova** [comment]
Thank you, Dom. I would appreciate your help with this one.

**Comment by DomHeinzeller** [comment]
@tanyasmirnova I see a whole bunch of variables that are different. It seems that some part of the `init` process still needs to be run. And that some of the variables in the `diag` type are not reset as they should at `fhzero` hours (especially MYNN stuff). I will try to fix the latter first and see if the results are still good for just those changes.

**Comment by tanyasmirnova** [comment]
Thank you for your work on this!

**Review by tanyasmirnova — APPROVED** [review]

**Comment by DomHeinzeller** [comment]
Regression testing on hera.intel using `rt_ccpp_gsd.conf`: first create new baseline, then verify against it (to test run-to-run reproducibility, restart reproducibility, ...): all tests pass.

[rt_ccpp_gsd_hera_intel_create.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5386117/rt_ccpp_gsd_hera_intel_create.log)
[rt_ccpp_gsd_hera_intel_verify.log](https://github.com/NOAA-GSD/ufs-weather-model/files/5386118/rt_ccpp_gsd_hera_intel_verify.log)

**Comment by DomHeinzeller** [comment]
Ready to merge!

**Pull request merged**
