### PR TITLE
Merge radar-tten for the tenth time

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
Temperature tendencies in microphysics scheme replaced with radar-derived values for the first N minutes of the model run.

### CODE REVIEW

**Comment by SamuelTrahanNOAA** [comment]
There are no conflicts in this branch. Github is confused. I will merge manually once reviews are complete.

**Comment by climbfuji** [comment]
> There are no conflicts in this branch. Github is confused. I will merge manually once reviews are complete.

This is the wrong target branch (it should be gsl/develop not gsd/develop - we should tag the latter branches and then delete them everywhere).

Further, the latest update of gsl/develop from the authoritative repos (i.e. the reverse of the merge of gsl/develop into the authoritative repos) has not yet happened. I am planning to do that tmw, your PR should come afterwards. Or, alternatively, you target your PRs directly for the authoritative repositories.

**Comment by SamuelTrahanNOAA** [comment]
> This is the wrong target branch (it should be gsl/develop not gsd/develop - we should tag the latter branches and then delete them everywhere).

This is now fixed.

**Comment by SamuelTrahanNOAA** [comment]
It took me a few minutes to fix it because the changeset was so long my web browser froze trying to list it.

**Comment by DomHeinzeller** [comment]
@SamuelTrahanNOAA It's all your's! The new hash dbdb629 in NOAA-GSL gsl/develop ufs-weather-model is identical to hash 194f044 in ufs-community develop ufs-weather-model (except `.gitmodules` in ufs-weather-model and fv3atm, and `CODEOWNERS` in ccpp-physics).

**Comment by hu5970** [comment]
Dom,

Thanks, It is great to have an identical version of the gsl/develop and
ufs-community develop.

Ming

**Comment by DomHeinzeller** [comment]
@SamuelTrahanNOAA Is it correct that you will create PRs to the authoritative repositories instead of gsl/develop? If yes, can I close your set of PRs to gsl/develop? Thanks.

**Comment by SamuelTrahanNOAA** [comment]
Closing this so I can do a PR to the community repository.

**Pull request closed without merging**
